
CREATE TABLE COMPANIA(
	codCompania INT IDENTITY(1,1) PRIMARY KEY,
	DNI VARCHAR(15),
	DigVerificacion INT,
	RazonSocial VARCHAR(40),
	NombreComercial VARCHAR(50),
	Logo IMAGE,
	Departamento VARCHAR(10),
	Municipio VARCHAR(10),
	BarrioVereda VARCHAR(60),
	Direccion VARCHAR(100),
	Telefono VARCHAR(8),
	Extension VARCHAR(4),
	Fax VARCHAR(8),
	Celular VARCHAR(10),
	Email VARCHAR(100),
	SitioWeb VARCHAR(100),
	Regimen INT,
	Estado INT,
	Banco INT,
	TipoCuenta INT,
	NumCuenta VARCHAR(20),
	UsuarioCrea INT,
	FechaRegistro DATE,
	HoraRegistro DATETIME,
	UsuarioModifica INT,
	FechaModificacion DATE,
	HoraModificacion DATETIME,
	numLic VARCHAR(4000) NOT NULL,
	FOREIGN KEY(Departamento) REFERENCES departamento(Codigo),
	FOREIGN KEY(Municipio) REFERENCES Municipio(Codigo),
	FOREIGN KEY(Estado) REFERENCES Estado(ID),
	FOREIGN KEY(Banco) REFERENCES banco(ID),
	FOREIGN KEY(TipoCuenta) REFERENCES tipoCuenta(ID),
	FOREIGN KEY(UsuarioCrea) REFERENCES Usuario(Codigo),
    FOREIGN KEY(UsuarioModifica) REFERENCES Usuario(Codigo),
	FOREIGN KEY(Regimen) REFERENCES Regimen(ID)
);


