CREATE TABLE Cliente(
Codigo int IDENTITY(1,1) PRIMARY KEY,
DNI bigint,
DigitoVerificacion int,
TipoPersona varchar(30),
TipoIdentificacion varchar(30),
RazonSocial varchar(60),
NombreComercial varchar(70),
Nombres varchar(35),
Apellidos varchar(40),
Departamento varchar(10),
Municipio varchar(10),
BarrioVereda varchar(60),
Direccion varchar(100),
TelefonoFijo varchar(8),
Extension varchar(4),
Fax varchar(8),
Celular1 varchar(10),
Celular2 varchar(10),
Email varchar(100),
SitioWeb varchar(100),
IVA varchar(10),
Estado int,Banco int,
TipoCuenta int,
NumeroCuenta varchar(20),
FechaRegistro date,
HoraRegistro Time,
FechaModificacion date, 
HoraModificacion time,
UsuarioCrea int,
UsuarioModifica int, 
Foreign key(Departamento) References Departamento(Codigo),
Foreign key(Municipio) References Municipio(Codigo),
Foreign key(Estado) References EstadoCliente(Codigo),
Foreign key(Banco) References Banco(ID),
Foreign key(TipoCuenta) References TipoCuenta(ID),
Foreign key(UsuarioCrea) References Usuario(Codigo),
Foreign key(UsuarioModifica) References Usuario(Codigo)
)